import type { ProjectData } from '../types';

export const mockProjects: ProjectData[] = [
  {
    id: '1',
    nome: 'Reforma do Studio - Noremati Pilates',
    tipo: 'Studio / Comercial',
    status: 'Em andamento',
    config: {
      empresa: 'Noremati Pilates Clássico',
      projeto: 'Reforma do Studio',
      documento: '12.345.678/0001-90',
      responsavel: 'Paulo Henrique',
      telefone: '(13) 99999-9999',
      email: 'contato@noremati.com.br',
      endereco: 'Av. Ana Costa, 450',
      cidade: 'Santos / SP',
      respObra: 'João Pedreiro',
      orcamento: 45000,
      inicio: '2026-09-01',
      fim: '2026-10-30',
    },
    obra: [
      { id: 's1', nome: 'Demolição de paredes', categoria: 'Demolição', prioridade: 'Alta', dependencia: '', status: 'Concluído', progresso: 100, previsto: 3000, inicio: '2026-09-01', fim: '2026-09-10', profissionalId: 'p1', observacao: '', fimReal: '2026-09-10', checkServico: true, checkConferido: true, checkLimpo: true, checkPagamento: true, checkPendencias: true },
      { id: 's2', nome: 'Reposicionar iluminação', categoria: 'Elétrica', prioridade: 'Média', dependencia: 's1', status: 'Em andamento', progresso: 50, previsto: 4000, inicio: '2026-09-12', fim: '2026-09-24', profissionalId: 'p2', observacao: '', fimReal: '', checkServico: true, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's3', nome: 'Trocar vasos sanitários', categoria: 'Hidráulica', prioridade: 'Média', dependencia: 's1', status: 'Em andamento', progresso: 30, previsto: 2500, inicio: '2026-09-15', fim: '2026-09-18', profissionalId: 'p4', observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's4', nome: 'Pintura do estúdio', categoria: 'Pintura', prioridade: 'Baixa', dependencia: 's2', status: 'Não iniciado', progresso: 0, previsto: 3500, inicio: '2026-09-25', fim: '2026-10-02', profissionalId: null, observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's5', nome: 'Instalação piso click', categoria: 'Piso', prioridade: 'Alta', dependencia: 's3', status: 'Não iniciado', progresso: 0, previsto: 5000, inicio: '2026-09-28', fim: '2026-10-05', profissionalId: null, observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's6', nome: 'Manutenção ar-condicionado', categoria: 'Climatização', prioridade: 'Média', dependencia: 's2', status: 'Contratado', progresso: 40, previsto: 3000, inicio: '2026-10-05', fim: '2026-10-15', profissionalId: null, observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's7', nome: 'Limpeza pós-obra', categoria: 'Limpeza', prioridade: 'Baixa', dependencia: 's4', status: 'Não iniciado', progresso: 0, previsto: 800, inicio: '2026-10-18', fim: '2026-10-25', profissionalId: null, observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's8', nome: 'Acabamentos finais', categoria: 'Acabamentos', prioridade: 'Média', dependencia: 's5', status: 'Não iniciado', progresso: 0, previsto: 2500, inicio: '2026-10-12', fim: '2026-10-20', profissionalId: null, observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
    ],
    profissionais: [
      { id: 'p1', nome: 'João Pedro', servico: 'Pedreiro / Demolição', telefone: '(13) 98888-1111', email: 'joao@email.com', status: 'Concluído' },
      { id: 'p2', nome: 'Carlos Eletricista', servico: 'Eletricista', telefone: '(13) 98888-2222', email: 'carlos@email.com', status: 'Em andamento' },
      { id: 'p3', nome: 'Marcos Pintor', servico: 'Pintor', telefone: '(13) 98888-3333', email: 'marcos@email.com', status: 'Cotação' },
      { id: 'p4', nome: 'Ana Encanadora', servico: 'Encanadora', telefone: '(13) 98888-4444', email: 'ana@email.com', status: 'Em andamento' },
      { id: 'p5', nome: 'Antonio Acabamentos', servico: 'Acabamentos / Geral', telefone: '(13) 98888-5555', email: 'antonio@pix.com', status: 'Em andamento' },
    ],
    jobs: [
      { id: 'j1', etapa_id: 's1', profissional_id: 'p1', valor: 3000, pago: 3000, forma: 'Pix', parcelas: '1x', chavePix: '', valorParcela: null, status: 'Concluído' },
      { id: 'j2', etapa_id: 's2', profissional_id: 'p2', valor: 2500, pago: 1500, forma: 'Pix', parcelas: '1x', chavePix: '', valorParcela: null, status: 'Em andamento' },
      { id: 'j3', etapa_id: 's3', profissional_id: 'p4', valor: 1800, pago: 800, forma: 'Em Dinheiro', parcelas: '1x', chavePix: '', valorParcela: null, status: 'Em andamento' },
      { id: 'j4', etapa_id: 's3', profissional_id: 'p1', valor: 1200, pago: 0, forma: 'Pix', parcelas: '1x', chavePix: '', valorParcela: null, status: 'Em andamento' },
      { id: 'j5', etapa_id: 's1', profissional_id: 'p5', valor: 5000, pago: 2000, forma: 'Pix', parcelas: '1x', chavePix: 'antonio@pix.com', valorParcela: null, status: 'Em andamento' },
      { id: 'j6', etapa_id: 's2', profissional_id: 'p5', valor: 3000, pago: 0, forma: 'Cartão', parcelas: '3x', chavePix: '', valorParcela: 1000, status: 'Em andamento' },
    ],
    materiais: [
      { id: 'm1', etapa_id: 's2', nome: 'Fios e cabos elétricos', categoria: 'Elétrica', fornecedorId: 'f1', quantidade: 100, unidade: 'm', unitario: 15, pago: 1500, data: '2026-09-12', status: 'Entregue' },
      { id: 'm2', etapa_id: 's3', nome: 'Tubos PVC 40mm', categoria: 'Hidráulica', fornecedorId: 'f2', quantidade: 20, unidade: 'm', unitario: 35, pago: 700, data: '2026-09-15', status: 'Entregue' },
      { id: 'm3', etapa_id: 's1', nome: 'Sacos de cimento', categoria: 'Demolição', fornecedorId: 'f1', quantidade: 10, unidade: 'caixa', unitario: 28, pago: 280, data: '2026-09-01', status: 'Entregue' },
    ],
    equipamentos: [
      { id: 'e1', etapa_id: 's1', nome: 'Martelete elétrico', quantidade: 1, valor: 10000, fornecedorId: 'f1', forma: 'Pix', chavePix: '', parcelas: '1x', valorParcela: null, compra: '2026-09-01', entrega: '2026-09-05', status: 'Comprado' },
      { id: 'e2', etapa_id: 's5', nome: 'Reformer Pilates', quantidade: 1, valor: 8000, fornecedorId: 'f3', forma: 'Cartão', chavePix: '', parcelas: '4x', valorParcela: 2000, compra: '2026-09-28', entrega: '2026-10-10', status: 'Comprado' },
      { id: 'e3', etapa_id: 's5', nome: 'Cadillac Pilates', quantidade: 1, valor: 12000, fornecedorId: 'f3', forma: 'Cartão', chavePix: '', parcelas: '6x', valorParcela: 2000, compra: '2026-09-28', entrega: '2026-10-15', status: 'Aguardando entrega' },
    ],
    coverImage: '',
    fornecedores: [
      { id: 'f1', nome: 'Casa do Construtor', telefone: '(13) 3222-1111', email: 'vendas@casadoconstrutor.com', site: '' },
      { id: 'f2', nome: 'Hidráulica Santos', telefone: '(13) 3222-3333', email: 'contato@hidraulicasantos.com', site: '' },
      { id: 'f3', nome: 'Pilates Pro Equipamentos', telefone: '(11) 4000-1234', email: 'comercial@pilatespro.com', site: 'pilatespro.com.br' },
    ],
    categoriasObra: ['Demolição', 'Alvenaria', 'Elétrica', 'Hidráulica', 'Iluminação', 'Pintura', 'Piso', 'Climatização', 'Limpeza', 'Acabamentos', 'Imprevistos'],
    categoriasObraExtra: [],
    categoriasMaterial: ['Demolição', 'Alvenaria', 'Elétrica', 'Hidráulica', 'Iluminação', 'Pintura', 'Piso', 'Climatização', 'Banheiros', 'Acabamentos', 'Limpeza', 'Ferragens e fixação', 'Outros'],
    categoriasMaterialExtra: [],
    imprevistos: [
      { id: 'i1', nome: 'Cano quebrado na parede', categoria: 'Hidráulica', valor: 500, impactoDias: 2, status: 'Aberto' },
      { id: 'i2', nome: 'Fio adicional para ar-condicionado', categoria: 'Elétrica', valor: 200, impactoDias: 0, status: 'Resolvido' },
    ],
    pagamentos: [
      { id: 'pa1', referencia: 'João - Demolição', tipo: 'Profissional', valor: 3000, vencimento: '2026-09-15', forma: 'PIX', status: 'Pago' },
      { id: 'pa2', referencia: 'Carlos - Elétrica (2ª parcela)', tipo: 'Profissional', valor: 1000, vencimento: '2026-09-25', forma: 'PIX', status: 'Pendente' },
      { id: 'pa3', referencia: 'Material hidráulico', tipo: 'Material', valor: 700, vencimento: '2026-09-28', forma: 'Boleto', status: 'Pendente' },
    ],
    admin: [
      { id: 'a1', nome: 'Abertura CNPJ', valor: 800, pago: 800, status: 'Pago' },
      { id: 'a2', nome: 'Contador - mensalidade', valor: 300, pago: 300, status: 'Pago' },
    ],
    checklist: [
      { id: 'c1', nome: 'Paredes e correções concluídas', feito: true, auto: false, sourceObraId: null },
      { id: 'c2', nome: 'Elétrica, tomadas e interruptores testados', feito: false, auto: false, sourceObraId: null },
      { id: 'c3', nome: 'Vasos, torneiras e hidráulica testados', feito: false, auto: false, sourceObraId: null },
      { id: 'c4', nome: 'Pintura revisada e sem retoques pendentes', feito: false, auto: false, sourceObraId: null },
      { id: 'c5', nome: 'Piso click e rodapés concluídos', feito: false, auto: false, sourceObraId: null },
      { id: 'c6', nome: 'Ar-condicionado revisado e funcionando', feito: false, auto: false, sourceObraId: null },
      { id: 'c7', nome: 'Limpeza pós-obra concluída', feito: false, auto: false, sourceObraId: null },
      { id: 'c8', nome: 'Vistoria final realizada', feito: false, auto: false, sourceObraId: null },
    ],
  },
  {
    id: '2',
    nome: 'Reforma Apartamento Centro',
    tipo: 'Apartamento',
    status: 'Em andamento',
    config: {
      empresa: 'Família Silva',
      projeto: 'Reforma Apartamento Centro',
      documento: '123.456.789-00',
      responsavel: 'Roberto Silva',
      telefone: '(13) 97777-1234',
      email: 'roberto.silva@email.com',
      endereco: 'R. Marechal Deodoro, 200, Apto 32',
      cidade: 'Santos / SP',
      respObra: 'Pedro Alvenaria',
      orcamento: 25000,
      inicio: '2026-08-15',
      fim: '2026-10-15',
    },
    obra: [
      { id: 's1', nome: 'Demolição e remoção', categoria: 'Demolição', prioridade: 'Alta', dependencia: '', status: 'Concluído', progresso: 100, previsto: 2000, inicio: '2026-08-15', fim: '2026-08-30', profissionalId: 'p1', observacao: '', fimReal: '2026-08-30', checkServico: true, checkConferido: true, checkLimpo: true, checkPagamento: true, checkPendencias: true },
      { id: 's2', nome: 'Alvenaria e reboco', categoria: 'Alvenaria', prioridade: 'Alta', dependencia: 's1', status: 'Em andamento', progresso: 60, previsto: 6000, inicio: '2026-08-25', fim: '2026-09-10', profissionalId: 'p1', observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's3', nome: 'Pintura completa', categoria: 'Pintura', prioridade: 'Média', dependencia: 's2', status: 'Não iniciado', progresso: 0, previsto: 3000, inicio: '2026-09-23', fim: '2026-10-01', profissionalId: null, observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
      { id: 's4', nome: 'Acabamento e instalações', categoria: 'Acabamentos', prioridade: 'Média', dependencia: 's2', status: 'Cotação', progresso: 20, previsto: 4000, inicio: '2026-10-01', fim: '2026-10-10', profissionalId: null, observacao: '', fimReal: '', checkServico: false, checkConferido: false, checkLimpo: false, checkPagamento: false, checkPendencias: false },
    ],
    profissionais: [
      { id: 'p1', nome: 'Pedro Alvenaria', servico: 'Pedreiro', telefone: '(13) 96666-5555', email: 'pedro@email.com', status: 'Em andamento' },
      { id: 'p2', nome: 'Lucia Pintora', servico: 'Pintora', telefone: '(13) 96666-6666', email: 'lucia@email.com', status: 'Cotação' },
    ],
    jobs: [
      { id: 'j1', etapa_id: 's1', profissional_id: 'p1', valor: 2000, pago: 2000, forma: 'Pix', parcelas: '1x', chavePix: '', valorParcela: null, status: 'Concluído' },
      { id: 'j2', etapa_id: 's2', profissional_id: 'p1', valor: 5000, pago: 3000, forma: 'Em Dinheiro', parcelas: '1x', chavePix: '', valorParcela: null, status: 'Em andamento' },
    ],
    materiais: [
      { id: 'm1', etapa_id: 's2', nome: 'Tijolos cerâmicos', categoria: 'Alvenaria', fornecedorId: 'f1', quantidade: 500, unidade: 'un', unitario: 2.5, pago: 1250, data: '2026-08-25', status: 'Entregue' },
      { id: 'm2', etapa_id: 's2', nome: 'Argamassa', categoria: 'Alvenaria', fornecedorId: 'f1', quantidade: 30, unidade: 'caixa', unitario: 45, pago: 1350, data: '2026-08-25', status: 'Entregue' },
    ],
    equipamentos: [],
    coverImage: '',
    fornecedores: [
      { id: 'f1', nome: 'Casa do Construtor', telefone: '(13) 3222-1111', email: 'vendas@casadoconstrutor.com', site: '' },
    ],
    categoriasObra: ['Demolição', 'Alvenaria', 'Elétrica', 'Hidráulica', 'Iluminação', 'Pintura', 'Piso', 'Climatização', 'Limpeza', 'Acabamentos', 'Imprevistos'],
    categoriasObraExtra: [],
    categoriasMaterial: ['Demolição', 'Alvenaria', 'Elétrica', 'Hidráulica', 'Iluminação', 'Pintura', 'Piso', 'Climatização', 'Banheiros', 'Acabamentos', 'Limpeza', 'Ferragens e fixação', 'Outros'],
    categoriasMaterialExtra: [],
    imprevistos: [],
    pagamentos: [
      { id: 'pa1', referencia: 'Pedro - Alvenaria (2ª parcela)', tipo: 'Profissional', valor: 2000, vencimento: '2026-09-25', forma: 'PIX', status: 'Pendente' },
    ],
    admin: [
      { id: 'a1', nome: 'Projeto legal', valor: 500, pago: 500, status: 'Pago' },
    ],
    checklist: [
      { id: 'c1', nome: 'Demolição concluída', feito: true, auto: false, sourceObraId: null },
      { id: 'c2', nome: 'Alvenaria finalizada', feito: false, auto: false, sourceObraId: null },
      { id: 'c3', nome: 'Pintura concluída', feito: false, auto: false, sourceObraId: null },
      { id: 'c4', nome: 'Acabamento e instalações', feito: false, auto: false, sourceObraId: null },
      { id: 'c5', nome: 'Limpeza final', feito: false, auto: false, sourceObraId: null },
    ],
  },
];
